employee_finder/urls.py
from django.urls import path
from . import views

app_name = 'employee_finder'

urlpatterns = [
   path('register/', views.RegisterView.as_view(), name='register'),
   path('login/', views.AuthLoginView.as_view(), name='login'),
   path('logout/', views.AuthLogoutView.as_view(), name='logout'),
   path('user_list/', views.UserListView.as_view(), name='user_list'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('library.urls')),
    path('hashtags/', include('hashtags.urls')),
    path('basket/', include('basket.urls')),
    path('library_parsing/', include('library_parsing.urls')),
    path('employee_finder/', include('employee_finder.urls')),
    path('recipes/', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
    document_root=settings.STATIC_ROOT)

recipes/models.py
from django.db import models

class Recipe(models.Model):
   title = models.CharField(max_length=255, verbose_name="Название рецепта")
   description = models.TextField(verbose_name="Описание рецепта")

   def __str__(self):
      return self.title

class Ingredient(models.Model):
   UNITS = [
      ('г', 'граммы'),
      ('кг', 'килограммы'),
      ('мл', 'миллилитры'),
      ('л', 'литры'),
      ('шт', 'штуки'),
   ]

   name = models.CharField(max_length=255, verbose_name="Название ингредиента")
   quantity = models.FloatField(verbose_name="Количество")
   unit = models.CharField(max_length=10, choices=UNITS, verbose_name="Единица измерения")
   recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients')

   def __str__(self):
      return f"{self.name} ({self.quantity} {self.unit})"

templates/components/footer.html
{% load static %}
<footer>
   © 2024 Ваш Сайт:
   <a class="text-reset fw-bold" href="#" style="color: yellow;">ВашСайт.com</a>
</footer>

templates/components/header.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top"
     style="background: linear-gradient(to right, #1a1919, #100f0f);">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="https://lh5.googleusercontent.com/yzWtzlXIlHfLjcFkr0S7UgmoX9HFoJ6VRszWZyEt-G85Gl5ID_XxoLX6Ji6E223S-EU2UUt2Y89uOwkm0tr8KkLQbM4Su17ln5HVBLaLHfxFIqm4DDpwmzPhfeAg1mja2Xdz7JkCvJqbpoEOT0CX8Cg"
                 alt="Logo" style="width: 40px; height: 40px;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/" style="color: yellow;">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'all_books' %}" style="color: yellow;">Хэш теги</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false" style="color: yellow;">
                        Мои заказы
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'create_order' %}">Добавить</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'orders_list' %}">Корзина</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link enable" href="{% url 'employee_finder:register' %}" style="color: yellow;">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link enable" href="{% url 'parse_list' %}" style="color: yellow;">Другие фильмы</a>
                    <a class="nav-link enable" href="{% url 'parse_form' %}" style="color: yellow;">Парсинг</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link enable" href="{% url 'recipe_list' %}" style="color: yellow;">Итоговая Контрольная работа</a>
                </li>
            </ul>
            <form action="{% url 'search' %}" method="GET" class="d-flex" role="search">
                <input class="form-control me-2" name="q" type="text" type="search" placeholder="Поиск" aria-label="Поиск">
                <button class="btn btn-outline-success" type="submit" style="color: yellow; border-color: yellow;">
                    Поиск
                </button>
            </form>
        </div>
    </div>
</nav>